name: Docker Image CI

on:
  push:
    branches:
      - "master"
    tags:
      - 'v*.*.*'  # Match version tags like v1.0.0
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWOR }}

      - name: Extract version number or branch name
        id: extract_ref
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
            echo "VERSION=${BRANCH_NAME}" >> $GITHUB_ENV
          fi

      - name: Sanitize version
        id: sanitize_version
        run: |
          VERSION=${{ env.VERSION }}
          # Replace invalid characters in the version/tag name
          SANITIZED_VERSION=$(echo "${VERSION}" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
          echo "SANITIZED_VERSION=${SANITIZED_VERSION}" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:${{ env.SANITIZED_VERSION }}

      - name: Push the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            my-image-name:${{ env.SANITIZED_VERSION }}
            my-image-name:latest

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: |
            Docker image version ${{ env.SANITIZED_VERSION }} released.
