name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:latest
      - name: Push the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: my-image-name:latest
